### ISSUE TITLE
code

### ISSUE THREAD

**Issue by ddy-ddy** [sameerreddy13/rlcheck#1]
Hello, author. After running your Python example code, I found your quick test case generation useful. How does your Java code change test objects? Is there a connection between the Java code and the Python code? Can I build a platform based on Java code in Python that can replace any test object?

**Comment by ddy-ddy** [comment]
Hello, author, for binary search tree code, do you convert the test code into data flow and then conduct reinforcement learning based test case generation? Or is it just code specific to that test object?

**Comment by carolemieux** [comment]
There is no connection between the Java and Python code. You can see that the Java code requires manually editing JQF generators:
- [Original JQF generator](https://github.com/sameerreddy13/rlcheck/blob/master/jqf/examples/src/main/java/edu/berkeley/cs/jqf/examples/js/JavaScriptCodeGenerator.java)
- [Modified RLCheck generator](https://github.com/sameerreddy13/rlcheck/blob/master/jqf/examples/src/main/java/edu/berkeley/cs/jqf/examples/js/JavaScriptRLGenerator.java)

Check out the main [JQF](https://github.com/rohanpadhye/jqf) repo for more Java generators

The python code in this repo is specific to the BST test object, it does not actually reconstruct data flow from the sequence of choices used to create the BST. I do not recommend to use the approach in the python code here to implement RLCheck, where you explicitly write a state abstraction function that converts choice sequences to state. You can see in [state_abstraction.py](https://github.com/sameerreddy13/rlcheck/blob/master/bst_example/state_abstraction.py) that it gets complicated.

If you're looking for a python framework in which to do RLCheck, we also have a python notebook tutorial outlining the BST example in the [atlas framework](https://github.com/rbavishi/atlas/blob/master/tutorials/03-rl-fuzz-testing-bst.ipynb).

Let us know if you have further questions.

**Comment by ddy-ddy** [comment]
Hello, author, I want to know how Java code works. I can't find the main function running in the library.

**Comment by carolemieux** [comment]
Here is the main function:
https://github.com/sameerreddy13/rlcheck/blob/a08686d9dc04eb0d0fc39c38b977577b6f0850f1/jqf/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/rl/RLDriver.java
