### ISSUE TITLE
question about bst example

### ISSUE THREAD

**Issue by Myse1f** [sameerreddy13/rlcheck#3]
Hi!
I have an question about bst_example. When selecting a value, why we need 3 learner with index [1,2,3].

In file `bst_fuzz.py`:
```python
def generate_tree(oracle, depth=0):
    value = oracle.Select(range(0, 11), 1)
    tree = BinarySearchTree(value) 
    if depth < MAX_DEPTH and \
            oracle.Select([True, False], 2):
        tree.left = generate_tree(oracle, depth+1)
    if depth < MAX_DEPTH and \
            oracle.Select([True, False], 3):
        tree.right = generate_tree(oracle, depth+1) 
    return tree
```
oracle. select require an index value, which create 3 learners while generating root, left and right value.

I'm not familar with reinforcement learning.  Forgive me if this is an trival problem.

**Comment by sameerreddy13** [comment]
The learner with index 1 selects the values of nodes in the tree(ranging from [0, 10]).  
The learner with index 2 selects whether or not to branch left.
The learner with index 3 selects whether or not to branch right.
